### ISSUE TITLE
Is it possible to rename the relationship types to custom names while importing the database?

### ISSUE THREAD

**Issue by shruti-palshikar** [jexp/neo4j-rdbms-import#7]
I migrated the database but it created relationship type names based on the foreign key relationships which dont make enough sense as a rlationship type. Is it possible to define the relationship type without having to delete all the relationship types and create new ones?

**Comment by jexp** [comment]
No that's not possible, without hacking the internals.

But you can change / override the rules for creating the relationship-names and re-run your import.

https://github.com/jexp/neo4j-rdbms-import/blob/master/src/main/java/org/neo4j/imports/Rules.java#L70
